/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/l3vpn-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.l3vpn.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module l3vpn-types.yang */
public class l3vpnTypes extends ConfNamespace {
    public static final int hash = 1516667804;
    public int hash() {
        return l3vpnTypes.hash;
    }

    public static final String id = "http://com/example/l3vpn-types";
    public String id() {
        return l3vpnTypes.id;
    }

    public static final String uri = "http://com/example/l3vpn-types";
    public String uri() {
        return l3vpnTypes.uri;
    }

    public static final String prefix = "l3vpn-types";
    public String prefix() {
        return l3vpnTypes.prefix;
    }

    public l3vpnTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _complete_success = 0;
    public static final String _complete_success_ = "complete-success";
    public static final int    _complete_failure = 1;
    public static final String _complete_failure_ = "complete-failure";
    public static final int    _undeployed = 2;
    public static final String _undeployed_ = "undeployed";
}
